services:
  chirpstack:
    image: leedarson/cartsbl:${ARCH}-v1.8.4
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
    depends_on:
      - postgres
      - emqx
      - redis
    environment:
      - MQTT_BROKER_HOST=emqx
      - MQTT_BROKER_PORT=${EMQX_PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - POSTGRESQL_HOST=postgres
    ports:
      - "${CHIRPSTACK_PORT}:${CHIRPSTACK_PORT}"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
  
  chirpstack-gateway-bridge-basicstation-na:
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-us915_1.toml
    ports:
      - "${CHIRPSTACK_GATEWAY_BRIDGE_PORT}:${CHIRPSTACK_GATEWAY_BRIDGE_PORT}"
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on:
      - emqx
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M

  chirpstack-gateway-bridge-basicstation-eu:
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-eu868.toml
    ports:
      - "3031:3001"
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on:
      - emqx
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M

  chirpstack-rest-api:
    image: chirpstack/chirpstack-rest-api:4
    restart: unless-stopped
    command: --server chirpstack:${CHIRPSTACK_PORT} --bind 0.0.0.0:${CHIRPSTACK_REST_API_PORT} --insecure
    ports:
      - "${CHIRPSTACK_REST_API_PORT}:${CHIRPSTACK_REST_API_PORT}"
    depends_on:
      - chirpstack
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - ./storage/postgresqldata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=chirpstack
      - POSTGRES_PASSWORD=chirpstack
      - POSTGRES_DB=chirpstack
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save 300 1 --save 60 100 --appendonly no
    volumes:
      - ./storage/redisdata:/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M

  emqx:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "${EMQX_PORT}:${EMQX_PORT}"
    volumes: 
      - ./configuration/mosquitto/config/:/mosquitto/config/
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M

volumes:
  postgresqldata:
    driver_opts:
      o: "size=256M"
  redisdata:
    driver_opts:
      o: "size=256M"
